"""engine_pin — single-source ENGINE_MD5 pin.

One constant, one home. The five prose-only suites import this value instead
of each carrying a duplicate hard-coded literal. When the engine legitimately
changes, re-aim this one line and the entire tooling suite re-anchors.

The pin is a hard-coded literal — never computed at runtime. A pin that
recomputes its own value from the file it is supposed to guard is vacuous:
it can never detect drift. The literal was recorded at the commit that first
introduced it and is updated only by a deliberate, human-approved task.
"""

ENGINE_MD5 = "b441421c938f8306773cd81a1859c1be"  # re-aimed @ engine-merge-base-enforcement (the engine EXECUTES the streams.md wave fork-base rule, two surfaces: cmd_check gains the wave-ledger section — a FILLED roster echo != base is FAIL unverified_fork_base at ANY status, a pending row is FAIL at status:merging but only WARN fork_base_pending at status:live, an off-template ledger is FAIL wave_ledger_malformed fail-closed; NEW read-only cmd_wave_verify [milestone] is the explicit merge-time gate — strict at any status, per-row report, refusals wave_not_found/wave_ambiguous, NEVER mutates WAVE.md or state.json. v4 re-freeze (close-gap-before-gate micro change-request, 6th refute N12): the status: label must itself start a field — preceded by start-of-line, whitespace, or the middle-dot separator; an embedded substatus: label is not a status field, so a header with no real status field is wave_ledger_malformed (no status). v3 re-freeze (second change-request, 5th refute FG-STATUS-BOUNDARY): wave header status is the EXACT token after status: terminated only by whitespace/the middle-dot separator/end-of-line and must equal live or merging — the unfilled template placeholder live|merging and suffix drift (live-ish) are wave_ledger_malformed naming the bad token, never parsed as a valid prefix, never a WARN downgrade. v2 re-freeze (change-request after heal_exhausted): echo column resolved by EXACTLY-ONE matching header label — more than one fork-base-matching column (e.g. a second 'fork-base-prev' label) is wave_ledger_malformed 'ambiguous fork-base columns' (ambiguity refusal, never first-wins; 4th refute N1/N10) — plus the six refute-discovered drift vectors pinned as suite fixtures. heal-1+2+3 redo: all()-token semantics on the echo cell (FG-1) + status parsed from the FIRST wave: header line ONLY — neither body prose (FG-2) nor a later wave:-prefixed body line (FG-3) can rescue a status-less header; base from the FIRST base: line same-line-token-only (Pex), echo column derived from the header's fork-base label — headerless roster or shifted column is malformed, never a silent row-skip (P1,P2b). Helpers _wave_ledgers/_parse_wave_ledger/_sha_match (sha match: exact or prefix, both >=7 hex). Census: wave-verify in test_min_pillar LIFECYCLE + _NONZERO_OK. Carries the prior engine-argv-portability re-bind (main parse_known_args + _rebind_optional_positionals; _opt_positionals markers incl. wave-verify). tool-agnostic — never runs git)
